function FX_PedsJamesbond(alive)
    local playerPed = PlayerPedId()
    local playerPos = GetEntityCoords(playerPed, false)
    local bondModel = GetHashKey("cs_milton")
    local vehModel = GetHashKey("JB700")
    local playerGroup = GetHashKey("PLAYER")
    local relationshipGroup = AddRelationshipGroup("_HOSTILE_BOND")
    SetRelationshipBetweenGroups(5, relationshipGroup, playerGroup)
    local heading = GetEntityHeading(IsPedInAnyVehicle(playerPed, false) and GetVehiclePedIsIn(playerPed, false) or playerPed)
    local xPos = math.sin(math.rad(360.0 - heading)) * 10.0
    local yPos = math.cos(math.rad(360.0 - heading)) * 10.0
    RequestModel(vehModel)
    while not HasModelLoaded(vehModel) do Citizen.Wait(0) end
    local veh = CreateVehicle(vehModel, playerPos.x - xPos, playerPos.y - yPos, playerPos.z, heading, true, false, false)
    SetVehicleEngineOn(veh, true, true, false)
    SetModelAsNoLongerNeeded(vehModel)
    local vel = GetEntityVelocity(playerPed)
    SetEntityVelocity(veh, vel.x, vel.y, vel.z)
    RequestModel(bondModel)
    while not HasModelLoaded(bondModel) do Citizen.Wait(0) end
    local bond = CreatePedInsideVehicle(veh, 4, bondModel, -1, true, false)
    SetModelAsNoLongerNeeded(bondModel)
    SetPedRelationshipGroupHash(bond, relationshipGroup)
    TaskSetBlockingOfNonTemporaryEvents(bond, true)
    SetPedHearingRange(bond, 9999.0)
    SetPedConfigFlag(bond, 281, true)
    SetPedCombatAttributes(bond, 5, true)
    SetPedCombatAttributes(bond, 46, true)
    SetPedSuffersCriticalHits(bond, false)
    GiveWeaponToPed(bond, GetHashKey("WEAPON_SWITCHBLADE"), 9999, true, true)
    GiveWeaponToPed(bond, GetHashKey("WEAPON_VINTAGEPISTOL"), 9999, true, true)
    GiveWeaponComponentToPed(bond, GetHashKey("WEAPON_VINTAGEPISTOL"), GetHashKey("COMPONENT_AT_PI_SUPP"))
    SetPedAccuracy(bond, 100)
    TaskCombatPed(bond, playerPed, 0, 16)
end
