function FX_SpawnGrieferjesus2(alive)
    local modelHash = -835930287
    local playerPed = PlayerPedId()
    local playerPos = GetEntityCoords(playerPed, false)
    local oppressorHash = GetHashKey("OPPRESSOR2")
    local group = AddRelationshipGroup("_HOSTILE_JESUS2")
    SetRelationshipBetweenGroups(5, group, GetHashKey("PLAYER"))
    SetRelationshipBetweenGroups(5, group, GetHashKey("CIVMALE"))
    SetRelationshipBetweenGroups(5, group, GetHashKey("CIVFEMALE"))
    RequestModel(oppressorHash)
    while not HasModelLoaded(oppressorHash) do Citizen.Wait(0) end
    local heading = GetEntityHeading(IsPedInAnyVehicle(playerPed, false) and GetVehiclePedIsIn(playerPed, false) or playerPed)
    local veh = CreateVehicle(oppressorHash, playerPos.x, playerPos.y, playerPos.z, heading, true, false, false)
    SetVehicleEngineOn(veh, true, true, false)
    SetVehicleModKit(veh, 0)
    for i = 0, 49 do
        local max = GetNumVehicleMods(veh, i)
        SetVehicleMod(veh, i, max > 0 and max - 1 or 0, false)
    end
    SetEntityProofs(veh, false, true, true, false, false, false, false, false)
    SetModelAsNoLongerNeeded(oppressorHash)
    RequestModel(modelHash)
    while not HasModelLoaded(modelHash) do Citizen.Wait(0) end
    local ped = CreatePedInsideVehicle(veh, 4, modelHash, -1, true, false)
    SetModelAsNoLongerNeeded(modelHash)
    SetPedRelationshipGroupHash(ped, group)
    SetPedHearingRange(ped, 9999.0)
    SetPedConfigFlag(ped, 281, true)
    SetPedCombatAttributes(ped, 3, false)
    SetPedCombatAttributes(ped, 5, true)
    SetPedCombatAttributes(ped, 46, true)
    SetEntityProofs(ped, false, true, true, false, false, false, false, false)
    SetPedCanBeKnockedOffVehicle(ped, 1)
    SetPedCanRagdollFromPlayerImpact(ped, false)
    SetRagdollBlockingFlags(ped, 5)
    SetPedSuffersCriticalHits(ped, false)
    GiveWeaponToPed(ped, GetHashKey("WEAPON_RAILGUN"), 9999, true, true)
    TaskCombatPed(ped, playerPed, 0, 16)
    SetPedFiringPattern(ped, 0xC6EE6B4C)
end
