local generated = {
    {id='meta_spawn_multiple_effects', name='Combo Time', fn='FX_MetaSpawnMultipleEffects', sync_mode=SyncMode.META, weight=10, meta={{key='additionalEffects', on=2, off=0}}},
    {id='meta_effect_duration_0_5x', name='0.5x Effect Duration', fn='FX_MetaEffectDuration05x', sync_mode=SyncMode.META, weight=10, meta={{key='durationModifier', on=0.5, off=1.0}}},
    {id='meta_effect_duration_2x', name='2x Effect Duration', fn='FX_MetaEffectDuration2x', sync_mode=SyncMode.META, weight=10, meta={{key='durationModifier', on=2.0, off=1.0}}},
    {id='meta_hide_chaos_ui', name="What's Happening??", fn='FX_MetaHideChaosUi', sync_mode=SyncMode.META, weight=10, meta={{key='hideChaosUI', on=true, off=false}}},
    {id='meta_nochaos', name='No Chaos', fn='FX_MetaNochaos', sync_mode=SyncMode.META, weight=10, meta={{key='disableChaos', on=true, off=false}}},
    {id='meta_re_invoke', name='Re-Invoke Previous Effects', fn='FX_MetaReInvoke', sync_mode=SyncMode.META, weight=10, short=true, meta={{key='additionalEffects', on=1, off=0}}},
    {id='meta_timerspeed_0_5x', name='0.5x Timer Speed', fn='FX_MetaTimerspeed05x', sync_mode=SyncMode.META, weight=10, meta={{key='timerModifier', on=0.5, off=1.0}}},
    {id='meta_timerspeed_2x', name='2x Timer Speed', fn='FX_MetaTimerspeed2x', sync_mode=SyncMode.META, weight=10, meta={{key='timerModifier', on=2.0, off=1.0}}},
    {id='meta_timerspeed_5x', name='5x Timer Speed', fn='FX_MetaTimerspeed5x', sync_mode=SyncMode.META, weight=5, short=true, meta={{key='timerModifier', on=5.0, off=1.0}}},
    {id='meta_votingmode_majority', name='Majority Voting', fn='FX_MetaVotingmodeMajority', sync_mode=SyncMode.META, weight=10, meta={{key='votingMode', on='majority', off='none'}}},
    {id='meta_votingmode_antimajority', name='Minority Voting', fn='FX_MetaVotingmodeAntimajority', sync_mode=SyncMode.META, weight=10, meta={{key='votingMode', on='antimajority', off='none'}}},
    {id='misc_airstrike', name='Airstrike Inbound', fn='FX_MiscAirstrike', sync_mode=SyncMode.VISUAL, weight=10},
    {id='world_blackhole', name='Black Hole', fn='FX_WorldBlackhole', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='world_blackout', name='Blackout', fn='FX_WorldBlackout', sync_mode=SyncMode.VISUAL, weight=10},
    {id='misc_boost_velocity', name='Speed Boost', fn='FX_MiscBoostVelocity', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='misc_clone_on_death', name='Resurrection Day', fn='FX_MiscCloneOnDeath', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='cocktail_shaker', name='Cocktail Shaker', fn='FX_CocktailShaker', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='misc_earthquake', name='Earthquake', fn='FX_MiscEarthquake', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='misc_esp', name='ESP', fn='FX_MiscEsp', sync_mode=SyncMode.VISUAL, weight=10},
    {id='misc_fakecrash', name='Fake Crash', fn='FX_MiscFakecrash', sync_mode=SyncMode.VISUAL, weight=10, instant=true},
    {id='misc_fireworks', name='Fireworks!', fn='FX_MiscFireworks', sync_mode=SyncMode.VISUAL, weight=10},
    {id='misc_flamethrower', name='Flamethrowers', fn='FX_MiscFlamethrower', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='misc_fps_limit', name='Console Experience', fn='FX_MiscFpsLimit', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='misc_get_towed', name='Get Towed', fn='FX_MiscGetTowed', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='misc_ghost_world', name='Ghost Town', fn='FX_MiscGhostWorld', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='misc_go_to_jail', name='Bad Boys', fn='FX_MiscGoToJail', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='lowgravity', name='Low Gravity', fn='FX_Lowgravity', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='verylowgravity', name='Very Low Gravity', fn='FX_Verylowgravity', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='insanegravity', name='Insane Gravity', fn='FX_Insanegravity', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='invertgravity', name='Invert Gravity', fn='FX_Invertgravity', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='misc_sideways_gravity', name='Sideways Gravity', fn='FX_MiscSidewaysGravity', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='misc_randomgravity', name='Random Gravity', fn='FX_MiscRandomgravity', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='misc_highpitch', name='High Pitch', fn='FX_MiscHighpitch', sync_mode=SyncMode.VISUAL, weight=10},
    {id='player_arenawarstheme', name='Play Arena Wars Theme', fn='FX_PlayerArenawarstheme', sync_mode=SyncMode.VISUAL, weight=10},
    {id='invertvelocity', name='Invert Current Velocity', fn='FX_MiscInvertvelocity', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='misc_jumpy_props', name='Jumpy Props', fn='FX_MiscJumpyProps', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='time_lag', name='Lag', fn='FX_TimeLag', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='misc_lowpitch', name='Low Pitch', fn='FX_MiscLowpitch', sync_mode=SyncMode.VISUAL, weight=10},
    {id='world_lowpoly', name='Low Render Distance', fn='FX_WorldLowpoly', sync_mode=SyncMode.VISUAL, weight=10},
    {id='meteorrain', name='Meteor Shower', fn='FX_Meteorrain', sync_mode=SyncMode.VISUAL, weight=10},
    {id='misc_midas', name='Midas Touch', fn='FX_MiscMidas', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='player_moneydrops', name='Money Rain', fn='FX_PlayerMoneydrops', sync_mode=SyncMode.LOCAL, weight=10},
    {id='misc_muffled_audio', name='Muffled Audio', fn='FX_MiscMuffledAudio', sync_mode=SyncMode.VISUAL, weight=10},
    {id='misc_news_team', name='News Team', fn='FX_MiscNewsTeam', sync_mode=SyncMode.SPAWN_SINGLE, weight=5, short=true},
    {id='player_nophone', name='No Phone', fn='FX_PlayerNophone', sync_mode=SyncMode.LOCAL, weight=10},
    {id='misc_nosky', name='No Sky', fn='FX_MiscNosky', sync_mode=SyncMode.VISUAL, weight=10},
    {id='nothing', name='Nothing', fn='FX_Nothing', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='misc_remove_water', name='Drought', fn='FX_MiscRemoveWater', sync_mode=SyncMode.VISUAL, weight=10},
    {id='misc_nowaypoint', name='Remove Waypoint', fn='FX_MiscNowaypoint', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='misc_oilleaks', name='Oil Trails', fn='FX_MiscOilleaks', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='misc_onebullet', name='One Bullet Mags', fn='FX_MiscOnebullet', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='misc_pause', name='Pause', fn='FX_MiscPause', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='misc_pay_respects', name='Pay Respects', fn='FX_MiscPayRespects', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='misc_portrait', name='Portrait Mode', fn='FX_MiscPortrait', sync_mode=SyncMode.VISUAL, weight=10},
    {id='misc_quick_sprunk_stop', name='Quick Sprunk Stop', fn='FX_MiscQuickSprunkStop', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='peds_rainbowweps', name='Rainbow Weapons', fn='FX_PedsRainbowweps', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='misc_rampjam', name='Ramp Jam', fn='FX_MiscRampjam', sync_mode=SyncMode.LOCAL, weight=10},
    {id='misc_random_waypoint', name='Set Random Waypoint', fn='FX_MiscRandomWaypoint', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='misc_credits', name='Roll Credits', fn='FX_MiscCredits', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='misc_solid_props', name='Solid Props', fn='FX_MiscSolidProps', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='misc_spawnufo', name='Spawn UFO', fn='FX_MiscSpawnufo', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='misc_spawnferriswheel', name='Spawn Ferris Wheel', fn='FX_MiscSpawnferriswheel', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='misc_spawn_orange_ball', name='Spawn Orange Ball', fn='FX_MiscSpawnOrangeBall', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='misc_spinning_props', name='Spinning Props', fn='FX_MiscSpinningProps', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='misc_stuffguns', name='Improvised Weaponry', fn='FX_MiscStuffguns', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='misc_superstunt', name='Super Stunt', fn='FX_MiscSuperstunt', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='chaosmode', name='Doomsday', fn='FX_Chaosmode', sync_mode=SyncMode.META, weight=5, short=true, meta={{key='additionalEffects', on=3, off=0}, {key='timerModifier', on=3.0, off=1.0}}},
    {id='misc_uturn', name='U-Turn', fn='FX_MiscUturn', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='misc_fakeuturn', name='Fake U-Turn', fn='FX_MiscFakeuturn', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='misc_vehicle_rain', name='Vehicle Rain', fn='FX_MiscVehicleRain', sync_mode=SyncMode.SPAWN_SINGLE, weight=5, short=true},
    {id='misc_weirdpitch', name='Weird Pitch', fn='FX_MiscWeirdpitch', sync_mode=SyncMode.VISUAL, weight=10},
    {id='world_whalerain', name='Whale Rain', fn='FX_WorldWhalerain', sync_mode=SyncMode.SPAWN_SINGLE, weight=10},
    {id='misc_witness_protection', name='Witness Protection', fn='FX_MiscWitnessProtection', sync_mode=SyncMode.SPAWN_SINGLE, weight=10},
    {id='peds_2x_animation_speed', name='2x Animation Speed', fn='FX_Peds2xAnimationSpeed', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_aimbot', name='Aimbot Peds', fn='FX_PedsAimbot', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_attackplayer', name='All Peds Attack Player', fn='FX_PedsAttackplayer', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_blind', name='Blind Peds', fn='FX_PedsBlind', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_bloody', name='Everyone Is Bloody', fn='FX_PedsBloody', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_busbois', name='Bus Bois', fn='FX_PedsBusbois', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_catguns', name='Catto Guns', fn='FX_PedsCatguns', sync_mode=SyncMode.SPAWN_SINGLE, weight=10},
    {id='peds_cops', name='All Peds Are Cops', fn='FX_PedsCops', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_drive_backwards', name='Peds Drive Backwards', fn='FX_PedsDriveBackwards', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_driveby', name='Peds Drive-By Player', fn='FX_PedsDriveby', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='peds_eternal_screams', name='Eternal Screams', fn='FX_PedsEternalScreams', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='peds_giverpg', name='Give Everyone An RPG', fn='FX_PedsGiverpg', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_stungun', name='Give Everyone A Stun Gun', fn='FX_PedsStungun', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_minigun', name='Give Everyone A Minigun', fn='FX_PedsMinigun', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_upnatomizer', name='Give Everyone An Up-N-Atomizer', fn='FX_PedsUpnatomizer', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_randomwep', name='Give Everyone A Random Weapon', fn='FX_PedsRandomwep', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_railgun', name='Give Everyone A Railgun', fn='FX_PedsRailgun', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_battleaxe', name='Give Everyone A Battle Axe', fn='FX_PedsBattleaxe', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='playerveh_exit', name='Everyone Exits Their Vehicles', fn='FX_PlayervehExit', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_explosive', name='Explosive Peds', fn='FX_PedsExplosive', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='player_explosivecombat', name='Explosive Combat', fn='FX_PlayerExplosivecombat', sync_mode=SyncMode.LOCAL, weight=10},
    {id='peds_flip', name='Spinning Peds', fn='FX_PedsFlip', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='player_famous', name='You Are Famous', fn='FX_PlayerFamous', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_frozen', name='Peds Are Brainless', fn='FX_PedsFrozen', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_give_props', name='Give Everyone A Random Prop', fn='FX_PedsGiveProps', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_grapple_guns', name='Gravity Guns', fn='FX_PedsGrappleGuns', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_gunsmoke', name='Gunsmoke', fn='FX_PedsGunsmoke', sync_mode=SyncMode.VISUAL, weight=10},
    {id='peds_hands_up', name='Hands Up!', fn='FX_PedsHandsUp', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_headless', name='Mannequins', fn='FX_PedsHeadless', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_hotcougars', name='Hot Cougars In Your Area', fn='FX_PedsHotcougars', sync_mode=SyncMode.SPAWN_SINGLE, weight=5, short=true},
    {id='peds_ignite', name='Ignite All Nearby Peds', fn='FX_PedsIgnite', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_intorandomvehs', name='Set Everyone Into Random Vehicles', fn='FX_PedsIntorandomvehs', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_invincible', name='Everyone Is Invincible', fn='FX_PedsInvincible', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_ghost', name='Everyone Is A Ghost', fn='FX_PedsGhost', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_jamesbond', name='Spawn Deadly Agent', fn='FX_PedsJamesbond', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_slidy', name='Slidy Peds', fn='FX_PedsSlidy', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_killerclowns', name='Killer Clowns', fn='FX_PedsKillerclowns', sync_mode=SyncMode.SPAWN_SINGLE, weight=5, short=true},
    {id='peds_launchnearby', name='Launch All Nearby Peds Up', fn='FX_PedsLaunchnearby', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_loosetrigger', name='Loose Triggers', fn='FX_PedsLoosetrigger', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_mercenaries', name='Mercenaries', fn='FX_PedsMercenaries', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_mindmg', name='Minimal Damage', fn='FX_PedsMindmg', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_minions', name='Minions', fn='FX_PedsMinions', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_mowermates', name='Mower Mates', fn='FX_PedsMowermates', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_nailguns', name='Nailguns', fn='FX_PedsNailguns', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='peds_flee', name='All Nearby Peds Are Fleeing', fn='FX_PedsFlee', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='player_noragdoll', name='No Ragdoll', fn='FX_PlayerNoragdoll', sync_mode=SyncMode.LOCAL, weight=10},
    {id='peds_not_menendez', name='Not Menendez!', fn='FX_PedsNotMenendez', sync_mode=SyncMode.VISUAL, weight=10},
    {id='peds_obliterate', name='Obliterate All Nearby Peds', fn='FX_PedsObliterate', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='player_ohko', name='One Hit KO', fn='FX_PlayerOhko', sync_mode=SyncMode.LOCAL, weight=10},
    {id='peds_phones', name="Whose Phone Is Ringing?", fn='FX_PedsPhones', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_prop_hunt', name='Prop Hunt', fn='FX_PedsPropHunt', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_spawn_quarreling_couple', name='Spawn Quarreling Couple', fn='FX_PedsSpawnQuarrelingCouple', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_ragdoll', name='Ragdoll Everyone', fn='FX_PedsRagdoll', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_sensitivetouch', name='Sensitive Touch', fn='FX_PedsSensitivetouch', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='peds_reflectivedamage', name='Friendly Fire', fn='FX_PedsReflectivedamage', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='peds_revive', name='Revive Dead Peds', fn='FX_PedsRevive', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_riot', name='Peds Riot', fn='FX_PedsRiot', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_scooterbrothers', name='Scooter Brothers', fn='FX_PedsScooterbrothers', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_slippery_peds', name="Can't Tie My Shoes", fn='FX_PedsSlipperyPeds', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='peds_smoketrails', name='Smoke Trails', fn='FX_PedsSmoketrails', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_angryalien', name='Spawn Angry Alien', fn='FX_PedsAngryalien', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_angry_chimp', name='Spawn Angry Chimp', fn='FX_SpawnAngryChimp', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_grieferjesus', name='Spawn Griefer Jesus', fn='FX_SpawnGrieferjesus', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_grieferjesus2', name='Spawn Extreme Griefer Jesus', fn='FX_SpawnGrieferjesus2', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_angryjimmy', name='Spawn Jealous Jimmy', fn='FX_PedsAngryjimmy', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_spawnballasquad', name='Spawn Balla Squad', fn='FX_PedsSpawnballasquad', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_spawn_biker', name='Spawn Biker', fn='FX_PedsSpawnBiker', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_compbrad', name='Spawn Companion Brad', fn='FX_SpawnCompbrad', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_chimp', name='Spawn Companion Chimp', fn='FX_SpawnChimp', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_chop', name='Spawn Companion Doggo', fn='FX_SpawnChop', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_comprnd', name='Spawn Random Companion', fn='FX_SpawnComprnd', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_spawndancingapes', name='Spawn Dance Troupe', fn='FX_PedsSpawndancingapes', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_spawnfancats', name='Spawn Fan Cats', fn='FX_PedsSpawnfancats', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_spawnrandomhostile', name='Spawn Random Enemy', fn='FX_PedsSpawnrandomhostile', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_spawnimrage', name='Spawn Impotent Rage', fn='FX_PedsSpawnimrage', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_spawn_juggernaut', name='Spawn Juggernaut', fn='FX_PedsSpawnJuggernaut', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_roasting', name='Get Roasted', fn='FX_PedsRoasting', sync_mode=SyncMode.SPAWN_SINGLE, weight=5, short=true},
    {id='peds_spawn_space_ranger', name='Spawn Space Ranger', fn='FX_PedsSpawnSpaceRanger', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='peds_sayhi', name='Friendly Neighborhood', fn='FX_PedsSayhi', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_insult', name='Unfriendly Neighborhood', fn='FX_PedsInsult', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_kifflom', name='Kifflom!', fn='FX_PedsKifflom', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_stop_stare', name='Stop and Stare', fn='FX_PedsStopStare', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_remweps', name='Remove Weapons From Everyone', fn='FX_PedsRemweps', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_tank_bois', name='Tanks A Lot', fn='FX_PedsTankBois', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='peds_toast', name="You're Toast", fn='FX_PedsToast', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='peds_portal_gun', name='Portal Guns', fn='FX_PedsPortalGun', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='playerveh_tprandompeds', name='Teleport Random Peds Into Current Vehicle', fn='FX_PlayervehTprandompeds', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='zombies', name='Explosive Zombies', fn='FX_Zombies', sync_mode=SyncMode.SPAWN_SINGLE, weight=10},
    {id='player_afk', name='AFK', fn='FX_PlayerAfk', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='player_aimbot', name='Aimbot', fn='FX_PlayerAimbot', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_break', name='Autopilot', fn='FX_PlayerBreak', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='player_bees', name='Bees', fn='FX_PlayerBees', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_blimp_strats', name='Blimp Strats', fn='FX_PlayerBlimpStrats', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_clone', name='Clone Player', fn='FX_PlayerClone', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_copyforce', name='Use The Force', fn='FX_PlayerCopyforce', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='player_dead_eye', name='Dead Eye', fn='FX_PlayerDeadEye', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_drunk', name='Drunk', fn='FX_PlayerDrunk', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_fakedeath', name='Fake Death', fn='FX_PlayerFakedeath', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_fling_player', name='Fling Player', fn='FX_PlayerFlingPlayer', sync_mode=SyncMode.VISUAL, weight=10, instant=true},
    {id='player_forcefield', name='Forcefield', fn='FX_PlayerForcefield', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='player_grav_sphere', name='Gravity Sphere', fn='FX_PlayerGravSphere', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='player_gta_2', name='GTA 2', fn='FX_PlayerGta2', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='player_hacking', name='Realistic Hacking', fn='FX_PlayerHacking', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_gravity', name='Gravity Field', fn='FX_PlayerGravity', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='player_heavyrecoil', name='Heavy Recoil', fn='FX_PlayerHeavyrecoil', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_heal', name='HESOYAM', fn='FX_PlayerHeal', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_ignite', name='Ignite Player', fn='FX_PlayerIgnite', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_illegalinnocence', name='Innocence Is Illegal', fn='FX_PlayerIllegalinnocence', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_tired', name="I'm So Tired", fn='FX_PlayerTired', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_invincible', name='Invincibility', fn='FX_PlayerInvincible', sync_mode=SyncMode.LOCAL, weight=10, runDisabled=true},
    {id='player_jump_jump', name='Jump! Jump!', fn='FX_PlayerJumpJump', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='player_keeprunning', name='Help My W Key Is Stuck', fn='FX_PlayerKeeprunning', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='player_kickflip', name='Kickflip', fn='FX_PlayerKickflip', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_laggy_camera', name='Delayed Camera', fn='FX_PlayerLaggyCamera', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_upupaway', name='Launch Player Up', fn='FX_PlayerUpupaway', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_lockcamera', name='Lock Camera', fn='FX_PlayerLockcamera', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_movementx5', name='5x Movement Speed', fn='FX_PlayerMovementx5', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_movementx10', name='10x Movement Speed', fn='FX_PlayerMovementx10', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_movementx05', name='0.5x Movement Speed', fn='FX_PlayerMovementx05', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='player_no_random_movement', name='Disable Random Direction', fn='FX_PlayerNoRandomMovement', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_nospecial', name='No Special Ability', fn='FX_PlayerNospecial', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_nosprint', name='No Sprint & No Jump', fn='FX_PlayerNosprint', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_pacifist', name='Pacifist', fn='FX_PlayerPacifist', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_poof', name='Deadly Aim', fn='FX_PlayerPoof', sync_mode=SyncMode.LOCAL, weight=10},
    {id='poorboi', name='Poor Boy', fn='FX_Poorboi', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_ragdoll', name='Ragdoll', fn='FX_PlayerRagdoll', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_ragdollondmg', name='Player Ragdolls When Shot', fn='FX_PlayerRagdollondmg', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_randclothes', name='Randomize Player Clothes', fn='FX_PlayerRandclothes', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_tp_stunt', name='Make Random Stunt Jump', fn='FX_PlayerTpStunt', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='veh_randomseat', name='Set Player Into Random Vehicle Seat', fn='FX_VehRandomseat', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_rapid_fire', name='Rapid Fire', fn='FX_PlayerRapidFire', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_rocket', name='Rocket Man', fn='FX_PlayerRocket', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_tpclosestveh', name='Set Player Into Closest Vehicle', fn='FX_PlayerTpclosestveh', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_setintorandveh', name='Set Player Into Random Vehicle', fn='FX_PlayerSetintorandveh', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_simeonsays', name='Simeon Says', fn='FX_PlayerSimeonsays', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='player_suicide', name='Suicide', fn='FX_PlayerSuicide', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_superrun', name='Super Run & Super Jump', fn='FX_PlayerSuperrun', sync_mode=SyncMode.LOCAL, weight=10},
    {id='tp_lsairport', name='Teleport To LS Airport', fn='FX_TpLsairport', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='tp_mazebanktower', name='Teleport To Top Of Maze Bank Tower', fn='FX_TpMazebank', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='tp_fortzancudo', name='Teleport To Fort Zancudo', fn='FX_TpFortzancudo', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='tp_mountchilliad', name='Teleport To Mount Chiliad', fn='FX_TpMountchilliad', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='tp_skyfall', name='Teleport To Heaven', fn='FX_TpSkyfall', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_tptowaypoint', name='Teleport To Waypoint', fn='FX_PlayerTptowaypoint', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_tptowaypointopposite', name='Teleport To The Opposite Side Of Waypoint', fn='FX_PlayerTptowaypointopposite', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_tpfront', name='Teleport Player A Few Meters', fn='FX_PlayerTpfront', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='tp_random', name='Teleport To Random Location', fn='FX_TpRandom', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='tp_mission', name='Teleport To Random Mission', fn='FX_TpMission', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='tp_fake', name='Fake Teleport', fn='FX_TpFake', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='tp_fakex2', name='Fake Fake Teleport', fn='FX_TpFakex2', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_tpeverything', name='Teleport Everything To Player', fn='FX_PlayerTpeverything', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='player_tp_to_everything', name='Teleporter Malfunction', fn='FX_PlayerTpToEverything', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='player_tp_store', name='Teleport to Random Store', fn='FX_PlayerTpStore', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_vr', name='Virtual Reality', fn='FX_PlayerVr', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='player_walkonwater', name='Walk On Water', fn='FX_PlayerWalkonwater', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_5stars', name='5 Wanted Stars', fn='FX_Player5stars', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_plus2stars', name='+2 Wanted Stars', fn='FX_PlayerPlus2stars', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_neverwanted', name='Never Wanted', fn='FX_PlayerNeverwanted', sync_mode=SyncMode.LOCAL, weight=10},
    {id='player_3stars', name='3 Wanted Stars', fn='FX_Player3stars', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_1star', name='1 Wanted Star', fn='FX_Player1star', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_fakestars', name='Fake Wanted Level', fn='FX_PlayerFakestars', sync_mode=SyncMode.VISUAL, weight=10, instant=true},
    {id='player_allweps', name='Give All Weapons', fn='FX_PlayerAllweps', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='player_zoomzoom_cam', name='Zoom Zoom Cam', fn='FX_PlayerZoomzoomCam', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='player_binoculars', name='Binoculars', fn='FX_PlayerBinoculars', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_bouncyradar', name='Bouncy Radar', fn='FX_ScreenBouncyradar', sync_mode=SyncMode.VISUAL, weight=10},
    {id='misc_dvdscreensaver', name='DVD Screensaver', fn='FX_MiscDvdscreensaver', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='player_flip_camera', name='Turn Turtle', fn='FX_PlayerFlipCamera', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='misc_flip_ui', name='Flipped HUD', fn='FX_MiscFlipUi', sync_mode=SyncMode.VISUAL, weight=10},
    {id='player_heatvision', name='Heat Vision', fn='FX_PlayerHeatvision', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_maximap', name='Maximap', fn='FX_ScreenMaximap', sync_mode=SyncMode.VISUAL, weight=10},
    {id='player_nightvision', name='Night Vision', fn='FX_PlayerNightvision', sync_mode=SyncMode.VISUAL, weight=10},
    {id='no_radar', name='No Radar', fn='FX_NoRadar', sync_mode=SyncMode.VISUAL, weight=10},
    {id='player_on_demand_cartoon', name='On-Demand TV', fn='FX_PlayerOnDemandCartoon', sync_mode=SyncMode.VISUAL, weight=10},
    {id='player_quake_fov', name='Quake FOV', fn='FX_PlayerQuakeFov', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_realfp', name='Real First Person', fn='FX_ScreenRealfp', sync_mode=SyncMode.VISUAL, weight=10},
    {id='player_sick_cam', name='I Feel Sick', fn='FX_PlayerSickCam', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='player_spin_camera', name='Spinning Camera', fn='FX_PlayerSpinCamera', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_mexico', name='Is This What Mexico Looks Like?', fn='FX_ScreenMexico', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_bright', name='Deep Fried', fn='FX_ScreenBright', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_fog', name='Extreme Fog', fn='FX_ScreenFog', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_lowrenderdist', name='Where Did Everything Go?', fn='FX_ScreenLowrenderdist', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_lsd', name='LSD', fn='FX_ScreenLsd', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_fullbright', name='Fullbright', fn='FX_ScreenFullbright', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_bubblevision', name='Bubble Vision', fn='FX_ScreenBubblevision', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_lsnoire', name='LS Noire', fn='FX_ScreenLsnoire', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_needglasses', name='I Need Glasses', fn='FX_ScreenNeedglasses', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='timecycle_fuzzy', name='Static', fn='FX_TimecycleFuzzy', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='timecycle_darkworld', name='A Dark World', fn='FX_TimecycleDarkworld', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_arc', name='Arced Screen', fn='FX_ScreenArc', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_colorfulworld', name='Colorful World', fn='FX_ScreenColorfulworld', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_dimwarp', name='Dimension Warp', fn='FX_ScreenDimwarp', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_fckautorotate', name='Goddamn Auto-Rotate', fn='FX_ScreenFckautorotate', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_foldedscreen', name='Folded Screen', fn='FX_ScreenFoldedscreen', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_fourthdimension', name='Fourth Dimension', fn='FX_ScreenFourthdimension', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_hueshift', name='Hue Shift', fn='FX_ScreenHueshift', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_invertedcolors', name='Inverted Colors', fn='FX_ScreenInvertedcolors', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_localcoop', name='Split Screen Co-op', fn='FX_ScreenLocalcoop', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_mirrored', name='Mirrored Screen', fn='FX_ScreenMirrored', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_rgbland', name='RGB Land', fn='FX_ScreenRgbland', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_screenfreakout', name='Screen Freakout', fn='FX_ScreenScreenfreakout', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_screenpotato', name='Potato', fn='FX_ScreenScreenpotato', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='screen_shatteredscreen', name='Shattered Screen', fn='FX_ScreenShatteredscreen', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_swappedcolors', name='Swapped Colors', fn='FX_ScreenSwappedcolors', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_textureless', name='Textureless', fn='FX_ScreenTextureless', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_tnpanel', name='TN Panel', fn='FX_ScreenTnpanel', sync_mode=SyncMode.VISUAL, weight=10},
    {id='screen_warpedcam', name='Warped Camera', fn='FX_ScreenWarpedcam', sync_mode=SyncMode.VISUAL, weight=5, short=true},
    {id='time_morning', name='Set Time To Morning', fn='FX_TimeMorning', sync_mode=SyncMode.VISUAL, weight=10},
    {id='time_day', name='Set Time To Daytime', fn='FX_TimeDay', sync_mode=SyncMode.VISUAL, weight=10},
    {id='time_evening', name='Set Time To Evening', fn='FX_TimeEvening', sync_mode=SyncMode.VISUAL, weight=10},
    {id='time_night', name='Set Time To Night', fn='FX_TimeNight', sync_mode=SyncMode.VISUAL, weight=10},
    {id='time_quickday', name='Timelapse', fn='FX_TimeQuickday', sync_mode=SyncMode.VISUAL, weight=10},
    {id='time_local_time', name='Set Time To System Time', fn='FX_TimeLocalTime', sync_mode=SyncMode.VISUAL, weight=10},
    {id='time_x02', name='x0.2 Gamespeed', fn='FX_TimeX02', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='time_x05', name='x0.5 Gamespeed', fn='FX_TimeX05', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='time_superhot', name='Superhot', fn='FX_TimeSuperhot', sync_mode=SyncMode.LOCAL, weight=10},
    {id='veh_30mphlimit', name='30MPH Speed Limit', fn='FX_Veh30mphlimit', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='vehs_honkconstant', name='All Vehicles Honk', fn='FX_VehsHonkconstant', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_upupaway', name='Launch All Vehicles Up', fn='FX_VehsUpupaway', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='vehs_beyblade', name='Beyblades', fn='FX_VehsBeyblade', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='veh_boostbrake', name='Boost Braking', fn='FX_VehBoostbrake', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='veh_bouncy', name='Bouncy Vehicles', fn='FX_VehBouncy', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='veh_brakeboost', name='Brake Boosting', fn='FX_VehBrakeboost', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='playerveh_breakdoors', name='Break Doors Of Every Vehicle', fn='FX_PlayervehBreakdoors', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='player_forcedcinematiccam', name='Cinematic Vehicle Cam', fn='FX_PlayerForcedcinematiccam', sync_mode=SyncMode.LOCAL, weight=10},
    {id='vehs_red', name='Red Traffic', fn='FX_VehsRed', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_blue', name='Blue Traffic', fn='FX_VehsBlue', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_green', name='Green Traffic', fn='FX_VehsGreen', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_chrome', name='Chrome Traffic', fn='FX_VehsChrome', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_pink', name='Hot Traffic', fn='FX_VehsPink', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_rainbow', name='Rainbow Traffic', fn='FX_VehsRainbow', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_cruise_control', name='Cruise Control', fn='FX_VehsCruiseControl', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='vehs_crumble', name='Crumbling Vehicles', fn='FX_VehsCrumble', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='vehs_detach_wheel', name='Detach Random Wheel', fn='FX_VehsDetachWheel', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='vehs_disassemble', name='Disassemble Current Vehicle', fn='FX_VehsDisassemble', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='vehs_x2engine', name='2x Vehicle Engine Speed', fn='FX_VehsX2engine', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_x10engine', name='10x Vehicle Engine Speed', fn='FX_VehsX10engine', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_x05engine', name='0.5x Vehicle Engine Speed', fn='FX_VehsX05engine', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_explode', name='Explode All Nearby Vehicles', fn='FX_VehsExplode', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='vehs_flyingcars', name='Flying Cars', fn='FX_VehsFlyingcars', sync_mode=SyncMode.LOCAL, weight=10},
    {id='traffic_fullaccel', name='Full Acceleration', fn='FX_TrafficFullaccel', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='traffic_gtao', name='Traffic Magnet', fn='FX_TrafficGtao', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_honkboost', name='Honk Boosting', fn='FX_VehsHonkboost', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_invincible', name='All Vehicles Are Invulnerable', fn='FX_VehsInvincible', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, runDisabled=true},
    {id='vehs_ghost', name='Invisible Vehicles', fn='FX_VehsGhost', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='veh_jesustakethewheel', name='Jesus Take The Wheel', fn='FX_VehJesustakethewheel', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='vehs_jumpy', name='Jumpy Vehicles', fn='FX_VehsJumpy', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='playerveh_killengine', name='Kill Engine Of Every Vehicle', fn='FX_PlayervehKillengine', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='vehs_lockdoors', name='Lock All Vehicles', fn='FX_VehsLockdoors', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='vehs_nogravity', name='Vehicles Have No Gravity', fn='FX_VehsNogravity', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='notraffic', name='No Traffic', fn='FX_Notraffic', sync_mode=SyncMode.VISUAL, weight=10},
    {id='vehs_ohko', name='Vehicles Explode On Impact', fn='FX_VehsOhko', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='playerveh_despawn', name='Remove Current Vehicle', fn='FX_PlayervehDespawn', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='playerveh_explode', name='Detonate Current Vehicle', fn='FX_PlayervehExplode', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='playerveh_lock', name='Lock Player Inside Vehicle', fn='FX_PlayervehLock', sync_mode=SyncMode.LOCAL, weight=10},
    {id='playerveh_poptires', name='Pop Tires Of Every Vehicle', fn='FX_PlayervehPoptires', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='veh_poptire', name='Random Tire Popping', fn='FX_VehPoptire', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='vehs_prop_models', name='Prop Cars', fn='FX_VehsPropModels', sync_mode=SyncMode.SPAWN_SINGLE, weight=10},
    {id='veh_randtraffic', name='Random Traffic', fn='FX_VehRandtraffic', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='playerveh_repair', name='Repair All Vehicles', fn='FX_PlayervehRepair', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='misc_replacevehicle', name='Replace Current Vehicle', fn='FX_MiscReplacevehicle', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='veh_repossession', name='Repossession', fn='FX_VehRepossession', sync_mode=SyncMode.LOCAL, weight=10, instant=true},
    {id='vehs_rotall', name='Flip All Vehicles', fn='FX_VehsRotall', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='vehs_slippery', name='Slippery Vehicles', fn='FX_VehsSlippery', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_spamdoors', name='Spammy Vehicle Doors', fn='FX_VehsSpamdoors', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='spawn_rhino', name='Spawn Rhino', fn='FX_SpawnRhino', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_adder', name='Spawn Adder', fn='FX_SpawnAdder', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_dump', name='Spawn Dump', fn='FX_SpawnDump', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_monster', name='Spawn Monster', fn='FX_SpawnMonster', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_bmx', name='Spawn BMX', fn='FX_SpawnBmx', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_tug', name='Spawn Tug', fn='FX_SpawnTug', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_cargo', name='Spawn Cargo Plane', fn='FX_SpawnCargo', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_bus', name='Spawn Bus', fn='FX_SpawnBus', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_blimp', name='Spawn Blimp', fn='FX_SpawnBlimp', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_buzzard', name='Spawn Buzzard', fn='FX_SpawnBuzzard', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_faggio', name='Spawn Faggio', fn='FX_SpawnFaggio', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_ruiner3', name='Spawn Ruined Ruiner', fn='FX_SpawnRuiner3', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_random', name='Spawn Random Vehicle', fn='FX_SpawnRandom', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_baletrailer', name='Spawn Bale Trailer', fn='FX_SpawnBaletrailer', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_romero', name="Where's The Funeral?", fn='FX_SpawnRomero', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='vehs_spawn_wizard_broom', name="You're A Wizard, Franklin", fn='FX_VehsSpawnWizardBroom', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='spawn_bluesultan', name='Spawn Blue Sultan', fn='FX_SpawnBluesultan', sync_mode=SyncMode.SPAWN_SINGLE, weight=10, instant=true},
    {id='veh_speed_goal', name='Need For Speed', fn='FX_VehSpeedGoal', sync_mode=SyncMode.LOCAL, weight=5, short=true},
    {id='vehs_tiny', name='Tiny Vehicles', fn='FX_VehsTiny', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='vehs_poptiresconstant', name="Now This Is Some Tire Poppin'", fn='FX_VehsPoptiresconstant', sync_mode=SyncMode.GLOBAL_OWNED, weight=5, short=true},
    {id='vehs_alarmloop', name='Alarmy Vehicles', fn='FX_VehsAlarmloop', sync_mode=SyncMode.GLOBAL_OWNED, weight=10},
    {id='playerveh_maxupgrades', name='Add Max Upgrades To Every Vehicle', fn='FX_PlayervehMaxupgrades', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='playerveh_randupgrades', name='Add Random Upgrades To Every Vehicle', fn='FX_PlayervehRandupgrades', sync_mode=SyncMode.GLOBAL_OWNED, weight=10, instant=true},
    {id='veh_weapons', name='Vehicles Shoot Rockets', fn='FX_VehWeapons', sync_mode=SyncMode.LOCAL, weight=10},
    {id='weather_extrasunny', name='Extra Sunny Weather', fn='FX_WeatherExtrasunny', sync_mode=SyncMode.VISUAL, weight=10},
    {id='weather_stormy', name='Stormy Weather', fn='FX_WeatherStormy', sync_mode=SyncMode.VISUAL, weight=10},
    {id='weather_foggy', name='Foggy Weather', fn='FX_WeatherFoggy', sync_mode=SyncMode.VISUAL, weight=10},
    {id='weather_neutral', name='Neutral Weather', fn='FX_WeatherNeutral', sync_mode=SyncMode.VISUAL, weight=10},
    {id='weather_snowy', name='Snowy Weather', fn='FX_WeatherSnowy', sync_mode=SyncMode.VISUAL, weight=10},
    {id='weather_randomizer', name='Disco Weather', fn='FX_WeatherRandomizer', sync_mode=SyncMode.VISUAL, weight=10},
    {id='world_snow', name='Snow', fn='FX_WorldSnow', sync_mode=SyncMode.VISUAL, weight=10},
}

for _, e in ipairs(generated) do
    Effects.Pool[#Effects.Pool + 1] = e
end

-- NOTE: Effects.FinalizeRegistry() is called by shared/effects_tuning.lua,
-- which loads after this file and applies flag corrections first.
