--[[
    AUTO-GENERATED by tools/transpile_effects.py
    DO NOT EDIT — run transpiler again to regenerate, then manually refine.
]]

local _chaosTranspilerFallbackNotice = {}

local function ChaosFallbackScreen(effectId)
    local modifiers = {
        screen_arc = 'underwater',
        screen_colorfulworld = 'BeastLaunch02',
        screen_dimwarp = 'Barry1_Stoned',
        screen_fckautorotate = 'spectator5',
        screen_foldedscreen = 'NG_filmic14',
        screen_fourthdimension = 'Spectator6',
        screen_hueshift = 'ArenaEMP',
        screen_invertedcolors = 'phone_cam8',
        screen_localcoop = 'ArenaWheelPurple01',
        screen_mirrored = 'CAMERA_secuirity',
        screen_rgbland = 'underwater_deep',
        screen_screenfreakout = 'drug_drive_blend01',
        screen_screenpotato = 'MP_Powerplay_blend',
        screen_shatteredscreen = 'damage',
        screen_swappedcolors = 'NG_filmic20',
        screen_textureless = 'yell_tunnel_nodirect',
        screen_tnpanel = 'Tunnel',
        screen_warpedcam = 'Drunk',
        misc_dvdscreensaver = 'scanline_cam_cheap',
        misc_flip_ui = 'CAMERA_BW',
    }
    local modifier = modifiers[effectId] or 'spectator5'
    SetTimecycleModifier(modifier)
    SetTimecycleModifierStrength(1.0)
end

local function ChaosFallbackMeta(effectId, active)
    local payload = nil
    if effectId == 'meta_spawn_multiple_effects' then
        payload = { key = 'additionalEffects', value = active and 2 or 0 }
    elseif effectId == 'meta_effect_duration_0_5x' then
        payload = { key = 'durationModifier', value = active and 0.5 or 1.0 }
    elseif effectId == 'meta_effect_duration_2x' then
        payload = { key = 'durationModifier', value = active and 2.0 or 1.0 }
    elseif effectId == 'meta_timerspeed_0_5x' then
        payload = { key = 'timerModifier', value = active and 0.5 or 1.0 }
    elseif effectId == 'meta_timerspeed_2x' then
        payload = { key = 'timerModifier', value = active and 2.0 or 1.0 }
    elseif effectId == 'meta_timerspeed_5x' then
        payload = { key = 'timerModifier', value = active and 5.0 or 1.0 }
    elseif effectId == 'meta_nochaos' then
        payload = { key = 'disableChaos', value = active }
    elseif effectId == 'meta_hide_chaos_ui' then
        payload = { key = 'hideChaosUI', value = active }
    elseif effectId == 'meta_votingmode_majority' then
        payload = { key = 'votingMode', value = active and 'majority' or 'none' }
    elseif effectId == 'meta_votingmode_antimajority' then
        payload = { key = 'votingMode', value = active and 'antimajority' or 'none' }
    end
    if payload then
        TriggerServerEvent('cc:meta_set', payload.key, payload.value)
    end
end

local function ChaosForEachVehicle(fn)
    for _, veh in ipairs(GetGamePool('CVehicle')) do
        if DoesEntityExist(veh) then
            fn(veh)
        end
    end
end

local function ChaosForEachPed(fn)
    for _, ped in ipairs(GetGamePool('CPed')) do
        if DoesEntityExist(ped) then
            fn(ped)
        end
    end
end

local function ChaosRunTimed(alive, onTick, onStop, waitMs)
    waitMs = waitMs or 0
    if alive then
        while alive() do
            onTick()
            Citizen.Wait(waitMs)
        end
    else
        onTick()
    end
    if onStop then
        onStop()
    end
end

local RANDOM_PED_MODELS = {
    "a_m_m_acult_01", "a_m_m_afriamer_01", "a_m_m_beach_02", "a_m_m_busicas_01",
    "a_m_m_farmer_01", "a_m_m_fatlatin_01", "a_m_m_hillbilly_02", "a_m_m_indian_01",
    "a_m_m_og_boss_01", "a_m_m_paparazzi_01", "a_m_m_rurmeth_01", "a_m_m_salton_04",
    "a_m_m_skater_01", "a_m_m_socenlat_01", "a_m_m_tourist_01", "a_m_o_acult_02",
    "a_m_o_beach_01", "a_m_o_salton_01", "a_m_y_acult_02", "a_m_y_beach_02",
    "a_m_y_beachvesp_02", "a_m_y_business_03", "a_m_y_cyclist_01", "a_m_y_eastsa_02",
    "a_m_y_genstreet_01", "a_m_y_genstreet_02", "a_m_y_hipster_01", "a_m_y_jetski_01",
    "a_m_y_mexthug_01", "a_m_y_motox_02", "a_m_y_musclbeac_01", "a_m_y_rurmeth_01",
    "a_m_y_salton_01", "a_m_y_skater_02", "a_m_y_stlat_01", "a_m_y_stwhi_02",
    "a_m_y_sunbathe_01", "a_m_y_surfer_01", "a_m_y_vindouche_01", "a_m_y_yoga_01",
    "a_f_m_beach_01", "a_f_m_fatcult_01", "a_f_m_salton_01", "a_f_m_skidrow_01",
    "a_f_m_tourist_01", "a_f_o_genstreet_01", "a_f_o_soucent_01", "a_f_y_beach_01",
    "a_f_y_hipster_01", "a_f_y_juggalo_01", "a_f_y_runner_01", "a_f_y_vinewood_04",
    "a_f_y_yoga_01", "s_m_m_autoshop_01", "s_m_m_bouncer_01", "s_m_m_chemsec_01",
    "s_m_m_ciasec_01", "s_m_m_dockwork_01", "s_m_m_highsec_01", "s_m_m_lifeinvad_01",
    "s_m_m_movprem_01", "s_m_m_pilot_02", "s_m_m_security_01", "s_m_m_ups_02",
    "s_m_y_airworker", "s_m_y_blackops_01", "s_m_y_construct_01", "s_m_y_fireman_01",
    "s_m_y_marine_01", "s_m_y_pilot_01", "s_m_y_prisoner_01",
}

local function _ChaosCreateRandomPed(x, y, z, heading)
    local modelName = RANDOM_PED_MODELS[math.random(#RANDOM_PED_MODELS)]
    local model = GetHashKey(modelName)
    RequestModel(model)
    local t = 20
    while not HasModelLoaded(model) and t > 0 do
        Citizen.Wait(50)
        t = t - 1
    end
    local ped = CreatePed(26, model, x, y, z, heading, true, false)
    SetModelAsNoLongerNeeded(model)
    return ped
end

local function _ChaosCreateHostilePed(model, weapon)
    local playerPed = PlayerPedId()
    local pos = GetEntityCoords(playerPed, false)
    local ped = CreatePed(26, model, pos.x, pos.y, pos.z, GetEntityHeading(playerPed), true, false)
    SetPedAsEnemy(ped, true)
    GiveWeaponToPed(ped, weapon, 9999, true, true)
    SetPedCombatAttributes(ped, 5, true)
    SetPedCombatAttributes(ped, 46, true)
    TaskCombatPed(ped, playerPed, 0, 16)
    SetPedFiringPattern(ped, 0xC6EE6B4C)
    return ped
end

function ChaosTranspilerFallback(effectId, effectName, alive)
    if not _chaosTranspilerFallbackNotice[effectId] then
        _chaosTranspilerFallbackNotice[effectId] = true
        print(('[CC] Fallback transpiler approximation active for %s (%s)'):format(effectName, effectId))
    end

    if effectId:find('^meta_') then
        ChaosFallbackMeta(effectId, true)
        if alive then
            while alive() do
                Citizen.Wait(250)
            end
        end
        ChaosFallbackMeta(effectId, false)
        return
    end

    if effectId:find('^screen_') or effectId == 'misc_flip_ui' or effectId == 'misc_dvdscreensaver' then
        ChaosFallbackScreen(effectId)
        if alive then
            while alive() do
                Citizen.Wait(250)
            end
        else
            Citizen.Wait(2500)
        end
        ClearTimecycleModifier()
        return
    end

    if effectId:find('pitch') or effectId:find('muffled') then
        ShakeGameplayCam('SMALL_EXPLOSION_SHAKE', 0.25)
        if alive then
            while alive() do
                SetGameplayCamShakeAmplitude(0.25)
                Citizen.Wait(250)
            end
            StopGameplayCamShaking(true)
        end
        return
    end

    if effectId == 'player_allweps' then
        local ped = PlayerPedId()
        local weapons = {
            GetHashKey("WEAPON_PISTOL"), GetHashKey("WEAPON_SMG"), GetHashKey("WEAPON_ASSAULTRIFLE"), GetHashKey("WEAPON_PUMPSHOTGUN"),
            GetHashKey("WEAPON_SNIPERRIFLE"), GetHashKey("WEAPON_RPG"), GetHashKey("WEAPON_GRENADE"), GetHashKey("WEAPON_MOLOTOV"),
        }
        for _, weapon in ipairs(weapons) do
            GiveWeaponToPed(ped, weapon, 999, false, false)
        end
        return
    end

    if effectId:find('5stars') or effectId:find('wanted_5') then
        SetPlayerWantedLevel(PlayerId(), 5, false)
        SetPlayerWantedLevelNow(PlayerId(), false)
        return
    end

    if effectId:find('3stars') or effectId:find('wanted_3') then
        SetPlayerWantedLevel(PlayerId(), 3, false)
        SetPlayerWantedLevelNow(PlayerId(), false)
        return
    end

    if effectId:find('clear_wanted') or effectId:find('never_wanted') then
        ClearPlayerWantedLevel(PlayerId())
        return
    end

    if effectId:find('superrun') then
        ChaosRunTimed(alive, function()
            SetRunSprintMultiplierForPlayer(PlayerId(), 1.49)
            SetSuperJumpThisFrame(PlayerId())
        end, function()
            SetRunSprintMultiplierForPlayer(PlayerId(), 1.0)
        end, 0)
        return
    end

    if effectId:find('ragdollondmg') then
        ChaosRunTimed(alive, function()
            local playerPed = PlayerPedId()
            if HasEntityBeenDamagedByAnyPed(playerPed) or HasEntityBeenDamagedByAnyVehicle(playerPed) then
                ClearEntityLastDamageEntity(playerPed)
                SetPedToRagdoll(playerPed, 750, 750, 0, true, true, false)
            end
        end, nil, 50)
        return
    end

    if effectId:find('vehs_honk') or effectId:find('alarmloop') or effectId:find('lockdoors') or effectId:find('nogravity') or effectId:find('ghost') or effectId:find('invincible') or effectId:find('slippery') then
        ChaosRunTimed(alive, function()
            ChaosForEachVehicle(function(veh)
                if effectId:find('vehs_honk') then
                    SetHornPermanentlyOn(veh)
                end
                if effectId:find('alarmloop') then
                    SetVehicleAlarm(veh, true)
                    StartVehicleAlarm(veh)
                end
                if effectId:find('lockdoors') then
                    SetVehicleDoorsLocked(veh, 2)
                end
                if effectId:find('nogravity') then
                    SetVehicleGravity(veh, false)
                end
                if effectId:find('ghost') then
                    SetEntityAlpha(veh, 80, false)
                end
                if effectId:find('invincible') then
                    SetEntityInvincible(veh, true)
                end
                if effectId:find('slippery') then
                    SetVehicleReduceGrip(veh, true)
                end
            end)
        end, function()
            ChaosForEachVehicle(function(veh)
                SetVehicleAlarm(veh, false)
                SetVehicleDoorsLocked(veh, 1)
                SetVehicleGravity(veh, true)
                ResetEntityAlpha(veh)
                SetEntityInvincible(veh, false)
                SetVehicleReduceGrip(veh, false)
            end)
        end, 100)
        return
    end

    if effectId:find('poptires') then
        ChaosRunTimed(alive, function()
            ChaosForEachVehicle(function(veh)
                for i = 0, 7 do
                    SetVehicleTyreBurst(veh, i, true, 1000.0)
                end
            end)
        end, function()
            ChaosForEachVehicle(function(veh)
                for i = 0, 7 do
                    SetVehicleTyreFixed(veh, i)
                end
            end)
        end, 400)
        return
    end

    if effectId:find('fullaccel') then
        ChaosRunTimed(alive, function()
            ChaosForEachVehicle(function(veh)
                SetVehicleForwardSpeed(veh, GetVehicleModelEstimatedMaxSpeed(GetEntityModel(veh)) * 1.5)
            end)
        end, nil, 250)
        return
    end

    if effectId:find('jumpy') or effectId:find('bouncy') then
        ChaosRunTimed(alive, function()
            ChaosForEachVehicle(function(veh)
                if math.random() < 0.15 and not IsEntityInAir(veh) then
                    ApplyForceToEntity(veh, 1, 0.0, 0.0, effectId:find('bouncy') and 20.0 or 10.0, 0.0, 0.0, 0.0, 0, true, true, true, false, true)
                end
            end)
        end, nil, 100)
        return
    end

    if effectId:find('killengine') then
        ChaosForEachVehicle(function(veh)
            SetVehicleEngineHealth(veh, 0.0)
        end)
        return
    end

    if effectId:find('earthquake') then
        ChaosRunTimed(alive, function()
            ShakeGameplayCam('LARGE_EXPLOSION_SHAKE', 0.35)
            ChaosForEachVehicle(function(veh)
                if math.random() < 0.05 then
                    ApplyForceToEntity(veh, 1, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0, 0, true, true, true, false, true)
                end
            end)
        end, function()
            StopGameplayCamShaking(true)
        end, 150)
        return
    end

    if effectId:find('fireworks') then
        ChaosRunTimed(alive, function()
            local pos = GetEntityCoords(PlayerPedId(), false)
            AddExplosion(pos.x + math.random(-20, 20), pos.y + math.random(-20, 20), pos.z + math.random(15, 30), 38, 0.0, false, false, 0.0, false)
        end, nil, 750)
        return
    end

    if effectId:find('poor') then
        SetPedMoney(PlayerPedId(), 0)
        return
    end

    if alive then
        while alive() do
            Citizen.Wait(250)
        end
    end
end

